package me.marcusslover.resourcepacker;

import me.marcusslover.resourcepacker.api.IResourcePacker;
import me.marcusslover.resourcepacker.core.internal.RPBlockRegistry;
import me.marcusslover.resourcepacker.core.internal.RPMode;
import me.marcusslover.resourcepacker.core.internal.RPPacker;
import me.marcusslover.resourcepacker.core.resource.ResourceHelper;

import java.util.List;

public class ResourcePacker implements IResourcePacker {

    @Override
    public void pack(RPPacker RPPacker) {
        /*Information for the build*/
        RPPacker.setPrefix("marcusslover");
        RPPacker.setName("Packer");
        RPPacker.setDescription(List.of("Generated by ResourcePacker"));
        RPPacker.setMode(RPMode.AUTOMATIC);

        /*Resources*/
        ResourceHelper r = RPPacker.resources();

        /*Blocks*/
        RPBlockRegistry b = RPPacker.blocks();
        //b.register(RPBlock.of("Dark Tile", r.get("dark_tile.png")));
    }
}
